### ISSUE TITLE
[Bug]: 订阅页面选项消失，只剩两个

### ISSUE THREAD

**Issue by Kirrito-k423** [dawn-lc/IwaraDownloadTool#186]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的脚本

### 描述你的问题

![image](https://github.com/dawn-lc/IwaraDownloadTool/assets/44373239/2fd3c30c-c732-49a2-b2e4-ee642bf72ee5)
如图发现没有"下载所选"等选项，这个bug还是特性呢？

### 如何复现

1. 前往 'https://www.iwara.tv/subscriptions/videos'
2. 发现没有"下载所选"等选项

### 使用的浏览器是？

Chrome

### 使用的脚本管理器是？

Tampermonkey

### 脚本的版本是？

3.2.5

### 下载模式是？

Others

### 相关日志

```Text
Iwara 批量下载工具加载完成公告: 重构以及调整配置界面，新增自动点赞功能，因存在违规风险，该功能默认关闭！如需使用请手动开启，你已经被警告过了！
main.bc2ccfe7f8466d814b12.js:2 Sentry enabled.
main.bc2ccfe7f8466d814b12.js:2 Build 3.0.50 at Sun, 17 Mar 2024 16:20:02 GMT
userscript.html?name=Iwara-Download-Tool.user.js&id=ca02a85c-34b6-4982-a94d-f675cf58ad6d:2083 
        
        
       GET https://www.googletagmanager.com/gtag/js?id=UA-37410039-11 net::ERR_CONNECTION_CLOSED
Node.appendChild @ userscript.html?name=Iwara-Download-Tool.user.js&id=ca02a85c-34b6-4982-a94d-f675cf58ad6d:2083
（匿名） @ main.bc2ccfe7f8466d814b12.js:2
（匿名） @ main.bc2ccfe7f8466d814b12.js:2
e @ main.bc2ccfe7f8466d814b12.js:2
44482 @ main.bc2ccfe7f8466d814b12.js:2
a @ main.bc2ccfe7f8466d814b12.js:2
（匿名） @ main.bc2ccfe7f8466d814b12.js:2
（匿名） @ main.bc2ccfe7f8466d814b12.js:2
（匿名） @ main.bc2ccfe7f8466d814b12.js:2
main.bc2ccfe7f8466d814b12.js:2 Service worker registered.
workbox-6716fad7.js:1 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://www.iwara.tv/chunk-163.7b8c0e7cdd5a8666fc77.js.map","status":403}]
    at L.C (https://www.iwara.tv/workbox-6716fad7.js:1:9969)
    at async L (https://www.iwara.tv/workbox-6716fad7.js:1:9567)
    at async L.q (https://www.iwara.tv/workbox-6716fad7.js:1:8708)
```

### 截图

![image](https://github.com/dawn-lc/IwaraDownloadTool/assets/44373239/0143aaec-6ed7-4738-b7f4-8d482c433c95)

**Comment by dawn-lc** [comment]
bug，在修

**Comment by dawn-lc** [comment]
@Kirrito-k423 更新至开发版看看是否修复

**Comment by Kirrito-k423** [comment]
开发版3.2.6修复这个问题了, good job
